"""FAP-Insurance Configuration — Adjuster-Facing Defaults"""
from dataclasses import dataclass
from typing import Dict, List

@dataclass
class PricingTier:
    name: str
    max_verifications_per_month: int
    price_per_verification: float
    monthly_cap: float
    features: List[str]

class InsuranceConfig:
    # Core API endpoint
    FAP_CORE_URL = "https://fap-core.onrender.com"

    # Verdict thresholds for insurance language
    STRICT_LABEL = "VERIFIED — Proceed with claim"
    PROBABLE_LABEL = "LIKELY VALID — Standard review"
    SUSPICIOUS_LABEL = "FLAGGED — Enhanced review required"
    QUARANTINE_LABEL = "FRAUD RISK — Deny / escalate to SIU"

    # Pricing tiers
    TIERS = {
        "pilot": PricingTier(
            name="Pilot Program",
            max_verifications_per_month=1000,
            price_per_verification=0.00,
            monthly_cap=0.00,
            features=[
                "1,000 free verifications",
                "Real-time API access",
                "Standard adjuster report",
                "Email support",
                "No contract"
            ]
        ),
        "starter": PricingTier(
            name="Independent Adjuster",
            max_verifications_per_month=5000,
            price_per_verification=0.10,
            monthly_cap=500.00,
            features=[
                "Up to 5,000 verifications/month",
                "Real-time API access",
                "Detailed adjuster report",
                "Priority email support",
                "CSV export"
            ]
        ),
        "carrier": PricingTier(
            name="Carrier License",
            max_verifications_per_month=50000,
            price_per_verification=0.08,
            monthly_cap=4000.00,
            features=[
                "Up to 50,000 verifications/month",
                "Real-time + batch API",
                "White-label adjuster report",
                "Dedicated support channel",
                "SIU integration webhook",
                "Quarterly fraud trend report"
            ]
        ),
        "enterprise": PricingTier(
            name="Enterprise",
            max_verifications_per_month=999999,
            price_per_verification=0.05,
            monthly_cap=0.00,  # Custom
            features=[
                "Unlimited verifications",
                "Custom scoring weights",
                "On-premise deployment option",
                "SLA guarantee",
                "Dedicated account manager",
                "API access to raw NOAA/GOES data"
            ]
        )
    }

    # Report defaults
    REPORT_LOGO_URL = ""
    REPORT_COMPANY_NAME = "FAP-Core Insurance Verification"
    REPORT_FOOTER = "Generated by FAP-Core v0.2.0 | Solar-verified provenance"

    # Outreach
    OUTREACH_SUBJECT_LINES = [
        "Cut your photo fraud review time by 80%",
        "That 'storm damage' photo might be from Google Images",
        "Free pilot: verify every claim photo in 3 seconds",
        "Your SIU team needs this solar anchor",
        "Stop paying for claims with fabricated timestamps"
    ]

config = InsuranceConfig()
